package com.projet.mobile.growth.rendu.model

enum class Muscles(val displayName: String) {
    SHINS("shins"),
    HANDS("hands"),
    STERNOCLEIDOMASTOID("sternocleidomastoid"),
    SOLEUS("soleus"),
    INNER_THIGHS("inner thighs"),
    LOWER_ABS("lower abs"),
    GRIP_MUSCLES("grip muscles"),
    ABDOMINALS("abdominals"),
    WRIST_EXTENSORS("wrist extensors"),
    WRIST_FLEXORS("wrist flexors"),
    LATISSIMUS_DORSI("latissimus dorsi"),
    UPPER_CHEST("upper chest"),
    ROTATOR_CUFF("rotator cuff"),
    WRISTS("wrists"),
    GROIN("groin"),
    BRACHIALIS("brachialis"),
    DELTOIDS("deltoids"),
    FEET("feet"),
    ANKLES("ankles"),
    TRAPEMIUS("trapezius"),
    REAR_DELTOIDS("rear deltoids"),
    CHEST("chest"),
    QUADRICEPS("quadriceps"),
    BACK("back"),
    CORE("core"),
    SHOULDERS("shoulders"),
    ANKLE_STABILIZERS("ankle stabilizers"),
    RHOMBOIDS("rhomboids"),
    OBLIQUES("obliques"),
    LOWER_BACK("lower back"),
    HIP_FLEXORS("hip flexors"),
    LEVATOR_SCAPULAE("levator scapulae"),
    ABDUCTORS("abductors"),
    SERRATUS_ANTERIOR("serratus anterior"),
    TRAPS("traps"),
    FOREARMS("forearms"),
    DELTS("delts"),
    BICEPS("biceps"),
    UPPER_BACK("upper back"),
    SPINE("spine"),
    CARDIO("cardiovascular system"),
    TRICEPS("triceps"),
    ADDUCTORS("adductors"),
    HAMSTRINGS("hamstrings"),
    GLUTES("glutes"),
    PECTORALS("pectorals"),
    CALVES("calves"),
    LATS("lats"),
    QUADS("quads"),
    ABS("abs"),
    NULL("")
}
